# Generated by Django 2.2 on 2019-04-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('dob', models.TextField(max_length=11)),
                ('gender', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('desg', models.CharField(max_length=50)),
            ],
        ),
    ]
