# Generated by Django 2.2 on 2019-04-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rno', models.IntegerField(blank=True, null=True)),
                ('heading', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('df', models.TextField(max_length=11)),
                ('dt', models.TextField(max_length=11)),
            ],
        ),
    ]
