# Generated by Django 2.2 on 2019-04-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='sender',
            field=models.EmailField(max_length=50),
        ),
    ]
