# Generated by Django 2.2 on 2019-04-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190408_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
