# Generated by Django 2.2 on 2019-04-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190408_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leave',
        ),
    ]
