# Generated by Django 2.2 on 2019-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_delete_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='le',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rno', models.IntegerField(blank=True, null=True)),
                ('heading', models.CharField(max_length=50)),
                ('sender', models.EmailField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('df', models.TextField(max_length=11)),
                ('dt', models.TextField(max_length=11)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
