# Generated by Django 2.2 on 2019-04-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='le',
            name='df',
            field=models.TextField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='le',
            name='dt',
            field=models.TextField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='le',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='le',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='le',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='le',
            name='sender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
