# Generated by Django 2.2 on 2019-04-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190408_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='lev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rno', models.IntegerField(blank=True, null=True)),
                ('heading', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('df', models.TextField(max_length=11, null=True)),
                ('dt', models.TextField(max_length=11, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='le',
        ),
    ]
