# Generated by Django 2.2 on 2019-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190408_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('desg', models.CharField(max_length=50)),
            ],
        ),
    ]
