# Generated by Django 2.2 on 2019-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lev',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lev',
            name='sender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
