# Generated by Django 2.2 on 2019-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190408_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='le',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
