# Generated by Django 2.2 on 2019-04-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='d',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=100)),
                ('pno', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('left', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=100)),
                ('pno', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('left', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
